# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  right_index_j1:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_index_j2:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_limb_j1:
    has_velocity_limits: true
    max_velocity: 2.0944
    has_acceleration_limits: false
    max_acceleration: 0
  right_limb_j2:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: false
    max_acceleration: 0
  right_limb_j3:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: false
    max_acceleration: 0
  right_limb_j4:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: false
    max_acceleration: 0
  right_limb_j5:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: false
    max_acceleration: 0
  right_limb_j6:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: false
    max_acceleration: 0
  right_limb_j7:
    has_velocity_limits: true
    max_velocity: 3.1416
    has_acceleration_limits: false
    max_acceleration: 0
  right_middle_j1:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_middle_j2:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_pinky_j1:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_pinky_j2:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_ring_j1:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_ring_j2:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_thumb_j1:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_thumb_j2:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0