wheeled_walker:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - x
      - y
      - theta
      - left_wheel_joint
      - right_wheel_joint
      - head_j1
      - head_j2
      - left_limb_j1
      - left_limb_j2
      - left_limb_j3
      - left_limb_j4
      - left_limb_j5
      - left_limb_j6
      - left_limb_j7
      - left_index_j1
      - left_middle_j1
      - left_ring_j1
      - left_thumb_j1
      - right_limb_j1
      - right_limb_j2
      - right_limb_j3
      - right_limb_j4
      - right_limb_j5
      - right_limb_j6
      - right_limb_j7
      - right_index_j1
      - right_middle_j1
      - right_ring_j1
      - right_thumb_j1
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: arm_jointstate_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - right_limb_j1
        - right_limb_j2
        - right_limb_j3
        - right_limb_j4
        - right_limb_j5
        - right_limb_j6
        - right_limb_j7
    - name: follow_joint_trajectory
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - right_limb_j1
        - right_limb_j2
        - right_limb_j3
        - right_limb_j4
        - right_limb_j5
        - right_limb_j6
        - right_limb_j7